plugins {
	id 'com.gradleup.shadow' version "8.3.0"
	id 'java-library'
	id 'application'
}

application {
	mainClass = project.mainClass
}

group = project.group
version = project.version

base {
	archivesName = project.archivesName
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
		url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
		content {
			includeGroup 'org.bukkit'
			includeGroup 'org.spigotmc'
		}
	}
	maven {
		name = "CodeMC"
		url = uri("https://repo.codemc.io/repository/maven-public/")
	}
	maven { url 'https://mvn.lumine.io/repository/maven-public/' }
}

dependencies {
	compileOnly "org.spigotmc:spigot-api:${project.spigot_api_version}"
	compileOnly "io.lumine:Mythic-Dist:${project.mythicmobs_version}"
	compileOnly "de.tr7zw:item-nbt-api-plugin:${project.nbt_api_version}"
	compileOnly "javassist:javassist:3.12.1.GA"
	//implementation "net.kyori:adventure-api:4.21.0"
	//implementation "net.kyori:adventure-text-minimessage:4.21.0"
}

processResources {
	def props = [
		"version"    : project.version,
		"main_class" : project.mainClass
	]

	inputs.properties(props)

	filesMatching("plugin.yml") {
		expand(props)
	}
}

tasks.shadowJar {
	configurations = [project.configurations.shadow]
}

tasks.named('jar') {
	from('LICENSE') {
		into('.')
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}