# © Phanisment | 2024
# Thanks for download this plugin, if you has
# questions or error, just ask me in discord.

# Dont't touch this!
# If you don't know what means of this.
version: 1.0

test:
  item: STONE
  displayname: "Test Item"
  modeldata: 1