name: ItemCaster
version: ${project.version}
author: Phanisment
description: Cast MythicMobs Skill with NBT item.
main: phanisment.itemcaster.Main
api-version: 1.20
depend: [MythicMobs, NBTAPI]
commands:
  itemcaster:
    description: Main command.
    permission: itemcaster.admin
    aliases: [ic, itemcast, itemc, icaster, icast]
permission:
  itemcaster.admin:
    description: Admin Permission.
    default: false