info:
  namespace: _itemcaster
items:
  back:
    display_name: back
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/back_arrow
  next:
    display_name: next
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/next_arrow
  previous:
    display_name: previous
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/previous_arrow
  create_item:
    display_name: back
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/create_item
  add:
    display_name: add
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/add
  ability:
    display_name: ability
    resource:
      material: stick
      generate: true
      textures:
      - gui/interface/ability

font_images:
  main:
    path: "gui/main.png"
    scale_ratio: 256
    y_position: 14
  edit:
    path: "gui/edit.png"
    scale_ratio: 256
    y_position: 14
  modifiers:
    path: "gui/modifiers.png"
    scale_ratio: 256
    y_position: 14