name: ItemCaster
version: 1.2.1
author: Phanisment
description: Cast MythicMobs Skill with NBT item.
main: io.phanisment.itemcaster.ItemCaster
api-version: 1.20
depend:
- MythicMobs
softdepend:
- PlaceholderAPI
- ItemsAdder
commands:
  itemcaster:
    description: Main command.
    permission: itemcaster.admin
    aliases: [itemcast, icaster, itemc, icast, ic]
permission:
  itemcaster.admin:
    description: Admin Permission.
    default: false