name: ItemSkillCaster
version: 1.0.0
author: Phanisment
description: Cast MythicMobs Skill with NBT item data
main: phanisment.itemcaster.Main
api-version: 1.20
depend: [MythicMobs, NBTAPI]
commands:
  itemskillcaster:
    description: Main command.
    aliases: [isc, itemsc]
permission:
  itemskillcaster.admin:
    description: Op permission.
    default: op