name: MagicArtifact
version: 1.0.0
author: Phanisment
description: Cast MythicMobs Skill with NBT item data
main: phanisment.artifact.Main
api-version: 1.20
depend: [MythicMobs, NBTAPI]
commands:
  magicartifact:
    description: Main command.
    aliases: [ma]
permission:
  magicartifact.admin:
    description: Admin Permission.
    default: op