name: Maven Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Build and Upload JARs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Set maven project ver
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
      - name: Build and package Maven project
        run: mvn clean package
      - name: Upload to the GitHub release
        uses: Shopify/upload-to-release@v1
        with:
          name: ItemCaster-${{ github.event.release.tag_name }}.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/java-archive

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: target/${{ steps.findjar.outputs.jarname }}
          name: ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          relations: NLuc7Jjh:required
          game_versions: 1.20.1
          release_type: alpha
          loaders: spigot, bukkit, paper, purpur
          featured: false 
          project_id: nyCjVsXk