name: Build and Upload to Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/ItemCaster-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}