name: Build and Upload to Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Modrinth Release
        uses: dsx137/modrinth-release-action@main
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRITH_TOKEN }}
        with:
          name: ItemSkillCaster
          project_id: nyCjVsXk
          loaders: bukkit, paper
          game_versions: 1.20.1
          version_number: 0.1
          files: |
             ./target/ItemNbtCaster-*.jar
          dependencies: Vl1uNAuy:required
          changelog: "some message"
          version_type: alpha
          featured: false
          status: 'draft' # or archived, draft, unlisted, scheduled, unknown
          requested_status: 'draft' # or archived, draft, unlisted
          delete_old_files: false # default true