name: Test Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests with Maven and Capture Logs
      run: |
        mvn test 2>&1 | tee test_log.txt || true
      continue-on-error: true
    - name: Send Logs to Discord
      run: |
        ERROR_LOG=$(tail -n 40 test_log.txt)
        ERROR_LOG=$(echo "$ERROR_LOG" | sed 's/"/\\"/g')
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"**Test Log** in repository \`${{ github.repository }}\` at commit \`${{ github.sha }}\`.\n\nLogs:\n\`\`\`$ERROR_LOG\`\`\`\nCheck details [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).\"}" \
          ${{ secrets.ERROR_WEBHOOK }}