name: Test Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests with Maven and Capture Logs
      run: |
        mvn test 2>&1 | tee test_log.txt || true
    - name: Display Test Log (For Debugging)
      run: cat test_log.txt
      continue-on-error: true
    - name: Send Logs to Discord
      run: |
        LOG=$(tail -n 40 test_log.txt)
        LOG=$(echo "$LOG" | sed 's/"/\\"/g' | sed 's/\\/\\\\/g')
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"**Test Log** in repository \`${{ github.repository }}\` at commit \`${{ github.sha }}\`.\n\nLogs:\n\`\`\`$LOG\`\`\`\nCheck details [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).\"}" \
          ${{ secrets.ERROR_WEBHOOK }}